# -*- coding: utf-8 -*-
"""Belajar Tree Based Pipeline Optimization Tools

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgeW5ejrlfGGzH1TcyrqIX0GaeOF8gT_

<h1>Belajar Tree Based Pipeline Optimization Tools</h1>
"""

!pip install tpot

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tpot import TPOTClassifier

df = pd.read_csv('/content/Wine.csv')
df.head()

target_class = "1"
X = df.loc[:,df.columns != target_class]
y = df.loc[:, target_class]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state=2021)

tpot = TPOTClassifier(generations=5, 
                      population_size=50, 
                      verbosity=2, 
                      n_jobs=-1)

tpot.fit(X_train, y_train)

tpot.score(X_test, y_test)

df2 = pd.read_csv('/content/customer_data.csv')

df2.head()

df2.shape

target_class = "label"
X = df2.loc[:,df2.columns != target_class]
y = df2.loc[:, target_class]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state=2021)

tpot.fit(X_train, y_train)

tpot.score(X_test, y_test)